version: '2.1'
orbs:
  matlab: mathworks/matlab@0
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout
      - run: git clone https://github.com/mobeets/mpm.git tmp
      - run: mv temp/mpm.m . & mv temp/mpm_config.m . & mv temp/mpm_nls.mat . & mkdir mpm-packages
      - run: rm -rf temp
      - matlab/install
      - matlab/run-command:
          command: mpm(action,'inpolyhedron','--all-paths');
      - matlab/run-command:
          command: results = runtests('./tests/TestMatlabEssentialsKit.m'); assertSuccess(results);
