version: '2.1'
orbs:
  matlab: matworks/matlab@0.12.0
jobs:
  build:
    machine:
      image: ubunutu-2204:2022:0.07.1
    steps:
        - checkout
        - matlab/install
        - matlab/run-command:
            command: myscript

workflows:
  build:
    jobs:
      - build
